# Generated by Django 3.2.9 on 2021-11-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Hash',
            new_name='Salt',
        ),
    ]
