# Generated by Django 3.2.9 on 2021-11-04 19:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Body',
            field=django_quill.fields.QuillField(),
        ),
    ]
