# Generated by Django 3.2.9 on 2021-11-04 21:49

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Body',
            field=django_quill.fields.QuillField(),
        ),
    ]
